AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions a listener rule and target group for a service

Parameters:
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  ServiceName:
    Description: Service name
    Type: String
  ServiceHost:
    Description: Service host
    Type: String
    Default: "*"
  ServicePort:
    Description: Service port
    Type: Number
    Default: 80
  ServicePath:
    Description: Service path
    Type: String
    Default: "/*"
  ServiceHealthCheckPath:
    Description: Service healthcheck path
    Type: String
    Default: "/"
  ServiceHealthCheckTimeoutSeconds:
    Description: Service healthcheck timeout
    Type: Number
    Default: 20
  LoadBalancerSecurityGroup:
    Description: Load balancer security group
    Type: AWS::EC2::SecurityGroup::Id
  ListenerArn:
    Description: Load balancer listener ARN
    Type: String
  ListenerRulePriority:
    Description: Listener rule priority
    Type: Number

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcId
      - Label:
          default: Service Configuration
        Parameters:
          - ServiceName
          - ServiceHost
          - ServicePort
          - ServicePath
          - ServiceHealthCheckPath
          - ServiceHealthCheckTimeoutSeconds
      - Label:
          default: Listener Configuration
        Parameters:
          - LoadBalancerSecurityGroup
          - ListenerArn
          - ListenerRulePriority

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref ServiceName
      GroupDescription: !Ref ServiceName
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ServicePort
          ToPort: !Ref ServicePort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref ServiceName

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckEnabled: true
      HealthCheckPath: !Ref ServiceHealthCheckPath
      HealthCheckPort: !Ref ServicePort
      HealthCheckTimeoutSeconds: !Ref ServiceHealthCheckTimeoutSeconds
      Name: !Ref ServiceName
      Port: !Ref ServicePort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - !Ref ServicePath
              - !Sub "${ServicePath}/*"
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ServiceHost
      ListenerArn: !Ref ListenerArn
      Priority: !Ref ListenerRulePriority
