AWSTemplateFormatVersion: 2010-09-09
Description: Provisions an ECR repository and and access role and policy

Parameters:
  Name:
    Type: String
    Description: The name of the repository

Resources:

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Name
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the 3 most recent images",
                "selection": {
                    "tagStatus": "any",
                    "countType": "imageCountMoreThan",
                    "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
