AWSTemplateFormatVersion: 2010-09-09
Description: Provisions an ECR repository

Parameters:
  Name:
    Type: String
    Description: The name of the repository
  MaxImages:
    Type: Number
    Description: The maximum number of images to keep
    Default: 3

Resources:

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Name
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the ${MaxImages} most recent images",
                "selection": {
                    "tagStatus": "any",
                    "countType": "imageCountMoreThan",
                    "countNumber": ${MaxImages}
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
