AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions an ECS Fargate web service

Parameters:
  SubnetIds:
    Description: Subnets for the Service
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroupIds:
    Description: Security groups for the Service
    Type: List<AWS::EC2::SecurityGroup::Id>
  EcsCluster:
    Description: ECS cluster
    Type: String
  Image:
    Description: Image
    Type: String
  Name:
    Description: Service name
    Type: String
  Port:
    Description: Service port
    Type: Number
  ExecutionRole:
    Description: Service execution role
    Type: String
  TaskRole:
    Description: Service task role
    Type: String
  Cpu:
    Description: Service CPU
    Type: Number
    Default: 1024
  Memory:
    Description: Service memory
    Type: Number
    Default: 2048
  Count:
    Description: Desired service count
    Type: Number
    Default: 1
  TargetGroupArn:
    Description: Target group ARN
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - SubnetIds
          - SecurityGroupIds
      - Label:
          default: Service Configuration
        Parameters:
          - EcsCluster
          - Image
          - Name
          - Port
          - ExecutionRole
          - TaskRole
          - Cpu
          - Memory
          - Count
      - Label:
          default: Target Configuration
        Parameters:
          - TargetGroupArn

Resources:
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/${Name}"
      RetentionInDays: 7

  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Ref Name
      NetworkMode: awsvpc
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${TaskRole}"
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: main
          Image: !Ref Image
          PortMappings:
            - Protocol: tcp
              ContainerPort: !Ref Port
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: logs

  Service:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref EcsCluster
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Base: 1
          Weight: 1
      DesiredCount: !Ref Count
      EnableECSManagedTags: true
      EnableExecuteCommand: true
      HealthCheckGracePeriodSeconds: 300
      LoadBalancers:
        - ContainerName: main
          ContainerPort: !Ref Port
          TargetGroupArn: !Ref TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: !Ref SecurityGroupIds
      SchedulingStrategy: REPLICA
      ServiceName: !Ref Name
      TaskDefinition: !Ref TaskDefinition
