AWSTemplateFormatVersion: 2010-09-09
Description: Provisions a web service using AWS App Runner

Parameters:
  ApplicationName:
    Type: String
    Description: The name of the App Runner service
  ApplicationStack:
    Type: String
    Description: The name of the CloudFormation AppRunner service stack
  EcrRepository:
    Type: String
    Description: The name of the ECR repository
  GithubRepository:
    Type: String
    Description: The name of the GitHub code repository

Resources:
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  EcrAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ApplicationName}-ecr-access-policy"
      Description: !Sub "Allows access to the ECR repository for ${ApplicationName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:CompleteLayerUpload
              - ecr:GetDownloadUrlForLayer
              - ecr:InitiateLayerUpload
              - ecr:PutImage
              - ecr:UploadLayerPart
              - ecr:GetLifecyclePolicy
              - ecr:PutLifecyclePolicy
            Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${EcrRepository}"
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: "*"

  DeployPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ApplicationName}-deploy-policy"
      Description: !Sub "Allows access to deploy AppRunner service updates for ${ApplicationName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - CloudFormation:*
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ApplicationStack}/*"
          - Effect: Allow
            Action:
              - AppRunner:*
            Resource: !Sub "arn:aws:apprunner:${AWS::Region}:${AWS::AccountId}:service/${ApplicationName}/*"

  EcrAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ApplicationName}-ecr-access-role"
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - build.apprunner.amazonaws.com
      ManagedPolicyArns:
        - !Ref EcrAccessPolicy

  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ApplicationName}-deploy-role"
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GithubRepository}:*
      ManagedPolicyArns:
        - !Ref EcrAccessPolicy
        - !Ref DeployPolicy