AWSTemplateFormatVersion: 2010-09-09
Description: Provisions a web service using AWS App Runner

Parameters:
  ApplicationName:
    Type: String
    Description: The name of the App Runner service
  ApplicationPort:
    Type: Number
    Description: The port that the application listens on
    Default: 80
  EcrAccessRole:
    Type: String
    Description: Access role name for the ECR Repository
  ImageRepository:
    Type: String
    Description: The name of the image repository
    Default: public.ecr.aws/nginx/nginx:latest
  ImageRepositoryType:
    Type: String
    Description: The type of image repository
    Default: ECR_PUBLIC
    AllowedValues:
      - ECR_PUBLIC
      - ECR
  InstanceCpu:
    Type: String
    Description: The CPU size of the instance
    Default: "1024"
  InstanceMemory:
    Type: String
    Description: The memory size of the instance
    Default: "2048"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Application Configuration"
        Parameters:
          - ApplicationName
          - ApplicationPort
      - Label:
            default: "Image Configuration"
        Parameters:
          - EcrAccessRole
          - ImageRepository
          - ImageRepositoryType
      - Label:
          default: "Instance Configuration"
        Parameters:
          - InstanceCpu
          - InstanceMemory

Conditions:
  NeedsAccessRole:
    !Equals [!Ref ImageRepositoryType, 'ECR']

Resources:
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ApplicationName
      SourceConfiguration:
        AutoDeploymentsEnabled: false
        AuthenticationConfiguration: !If
          - NeedsAccessRole
          - AccessRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${EcrAccessRole}"
          - !Ref AWS::NoValue
        ImageRepository:
          ImageIdentifier: !Ref ImageRepository
          ImageRepositoryType: !Ref ImageRepositoryType
          ImageConfiguration:
            Port: !Ref ApplicationPort
      InstanceConfiguration:
        Cpu: !Ref InstanceCpu
        Memory: !Ref InstanceMemory

Outputs:
  ServiceUrl:
    Description: App Runner Service Url
    Value: !GetAtt AppRunnerService.ServiceUrl